spring.application.name=api-gateway

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/api-gateway/protocol/openid-connect/certs}

server.port=8080

logging.level.ROOT=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.security=INFO
