services:
  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - gateway-network
    depends_on:
      - user-service
      - account-service

  user-service:
    build: ../user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:postgres@postgres:5432/postgres
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - KEYCLOAK_URL=http://keycloak:8080/realms/api-gateway
    networks:
      - gateway-network
    depends_on:
      - postgres
      - keycloak

  account-service:
    build: ../account-service
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - gateway-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gateway-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - gateway-network

volumes:
  postgres_data:

networks:
  gateway-network:
    driver: bridge