spring.application.name=user-service
spring.threads.virtual.enabled=true

server.port=8082

# R2DBC PostgreSQL Configuration
spring.r2dbc.url=r2dbc:postgresql://postgres:postgres@localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Initialize schema
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/api-gateway}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=INFO
logging.level.com.tgr.userservice=DEBUG