### 1. Get JWT token from Keycloak
# @name token
POST http://localhost:8180/realms/api-gateway/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=api-gateway-client&client_secret=api-gateway-secret&username={{username}}&password={{password}}

### 2. Get User by ID (Authenticated via Gateway)
GET http://localhost:8080/users/1
Accept: application/json
Authorization: Bearer {{$auth.token("gateway-config")}}

### 3. Create a new User (Authenticated via Gateway)
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{$auth.token("gateway-config")}}

{
  "name": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "taxId": "000000001",
  "password": "password123",
  "role": "USER"
}

### 4. List all Users (Authenticated via Gateway)
GET http://localhost:8080/users
Accept: application/json
Authorization: Bearer {{$auth.token("gateway-config")}}

### 5. Get Accounts (Authenticated via Gateway)
GET http://localhost:8080/accounts
Accept: application/json
Authorization: Bearer {{$auth.token("gateway-config")}}