spring.application.name=account-service
spring.threads.virtual.enabled=true

server.port=8081

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/api-gateway}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=INFO