spring.application.name=account-service
spring.threads.virtual.enabled=true

server.port=8081

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/api-gateway/protocol/openid-connect/certs}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=INFO